# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Plant More Trees', folder: 'pages', file: 'contribute.html'}

social:
- {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'next'
  previous_page: 'previous'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
